AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-test-result-collector

  Sample SAM Template for aws-test-result-collector
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ResultCollectorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: result-collector/
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ResultCollector:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /collect
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ResultCollectorApi:
    Description: "API Gateway endpoint URL for Prod stage for Result Collector function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/collect/"
  ResultCollectorFunction:
    Description: "Result Collector Lambda Function ARN"
    Value: !GetAtt ResultCollectorFunction.Arn
  ResultCollectorFunctionIamRole:
    Description: "Implicit IAM Role created for Result Collector function"
    Value: !GetAtt ResultCollectorFunctionRole.Arn
